spring:
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire:  3
  datasource:
    url: jdbc:mysql://localhost:3306/studentVisit
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
