spring:
  mail:
    host: smtp.163.com
    username: 18595101277@163.com
    password: DWQYPGDPPPPSENMN
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire:  3
  datasource:
    url: jdbc:mysql://localhost:3306/studentVisit
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
